export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';
export const FETCH_ALL_POSTS_FULFILLED = 'FETCH_ALL_POSTS_FULFILLED';
export const FETCH_ALL_POSTS_REJECTED = 'FETCH_ALL_POSTS_REJECTED';
export const FETCH_ALL_POSTS_PENDING = 'FETCH_ALL_POSTS_PENDING';

export const SUBMIT_USER = 'SUBMIT_USER';
export const SUBMIT_USER_FULFILLED = 'SUBMIT_USER_FULFILLED';
export const SUBMIT_USER_PENDING = 'SUBMIT_USER_PENDING';
export const SUBMIT_USER_REJECTED = 'SUBMIT_USER_REJECTED';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED';
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED';

export const USER_LOGIN_STATUS = 'USER_LOGIN_STATUS';
export const USER_LOGIN_STATUS_FULFILLED = 'USER_LOGIN_STATUS_FULFILLED';
export const USER_LOGIN_STATUS_REJECTED = 'USER_LOGIN_STATUS_REJECTED';
export const USER_LOGIN_STATUS_PENDING = 'USER_LOGIN_STATUS_PENDING';