export const FETCH_ALL_POSTS = 'FETCH_ALL_POSTS';
export const FETCH_ALL_POSTS_FULFILLED = 'FETCH_ALL_POSTS_FULFILLED';
export const FETCH_ALL_POSTS_REJECTED = 'FETCH_ALL_POSTS_REJECTED';
export const FETCH_ALL_POSTS_PENDING = 'FETCH_ALL_POSTS_PENDING';

export const SUBMIT_USER = 'SUBMIT_USER';
export const SUBMIT_USER_FULFILLED = 'SUBMIT_USER_FULFILLED';
export const SUBMIT_USER_PENDING = 'SUBMIT_USER_PENDING';
export const SUBMIT_USER_REJECTED = 'SUBMIT_USER_REJECTED';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED';
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED';

export const USER_LOGIN_STATUS = 'USER_LOGIN_STATUS';
export const USER_LOGIN_STATUS_FULFILLED = 'USER_LOGIN_STATUS_FULFILLED';
export const USER_LOGIN_STATUS_REJECTED = 'USER_LOGIN_STATUS_REJECTED';
export const USER_LOGIN_STATUS_PENDING = 'USER_LOGIN_STATUS_PENDING';

export const FETCH_PROFILE_DETAILS = 'FETCH_PROFILE_DETAILS';
export const FETCH_PROFILE_DETAILS_FULFILLED = 'FETCH_PROFILE_DETAILS_FULFILLED';
export const FETCH_PROFILE_DETAILS_PENDING = 'FETCH_PROFILE_DETAILS_PENDING';
export const FETCH_PROFILE_DETAILS_REJECTED = 'FETCH_PROFILE_DETAILS_REJECTED';

export const USER_COMMENT = 'USER_COMMENT';
export const USER_COMMENT_FULFILLED = 'USER_COMMENT_FULFILLED';
export const USER_COMMENT_PENDING = 'USER_COMMENT_PENDING';
export const USER_COMMENT_REJECTED = 'USER_COMMENT_REJECTED';

export const FETCH_COMMENTS_FOR_POST = 'FETCH_COMMENTS_FOR_POST';
export const FETCH_COMMENTS_FOR_POST_FULFILLED = 'FETCH_COMMENTS_FOR_POST_FULFILLED';
export const FETCH_COMMENTS_FOR_POST_REJECTED = 'FETCH_COMMENTS_FOR_POST_REJECTED';
export const FETCH_COMMENTS_FOR_POST_PENDING = 'FETCH_COMMENTS_FOR_POST_PENDING';

export const HANDLE_LIKES = 'HANDLE_LIKES';
export const HANDLE_LIKES_FULFILLED = 'HANDLE_LIKES_FULFILLED';
export const HANDLE_LIKES_REJECTED = 'HANDLE_LIKES_REJECTED';
export const HANDLE_LIKES_PENDING = 'HANDLE_LIKES_PENDING';

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPLOAD_IMAGE_FULFILLED = 'UPLOAD_IMAGE_FULFILLED';
export const UPLOAD_IMAGE_REJECTED = 'UPLOAD_IMAGE_REJECTED';
export const UPLOAD_IMAGE_PENDING = 'UPLOAD_IMAGE_PENDING';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_PENDING = 'CREATE_POST_PENDING';
export const CREATE_POST_FULFILLED = 'CREATE_POST_FULFILLED';
export const CREATE_POST_REJECTED = 'CREATE_POST_REJECTED';

export const FOLLOW_ACCOUNT = 'FOLLOW_ACCOUNT';
export const FOLLOW_ACCOUNT_PENDING = 'FOLLOW_ACCOUNT_PENDING';
export const FOLLOW_ACCOUNT_FULFILLED = 'FOLLOW_ACCOUNT_FULFILLED';
export const FOLLOW_ACCOUNT_REJECTED = 'FOLLOW_ACCOUNT_REJECTED';

export const FAVORITE_POST = 'FAVORITE_POST';
export const FAVORITE_POST_PENDING = 'FAVORITE_POST_PENDING';
export const FAVORITE_POST_FULFILLED = 'FAVORITE_POST_FULFILLED';
export const FAVORITE_POST_REJECTED = 'FAVORITE_POST_REJECTED';

export const SET_PAGE_HEADER = 'SET_PAGE_HEADER';

export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_ALL_USERS_PENDING = 'FETCH_ALL_USERS_PENDING';
export const FETCH_ALL_USERS_FULFILLED = 'FETCH_ALL_USERS_FULFILLED';
export const FETCH_ALL_USERS_REJECTED = 'FETCH_ALL_USERS_REJECTED';